### ISSUE TITLE
Adding "STEPS TO CONTRIBUTE"

### ISSUE THREAD

**Issue by saubhagya-gupta** [102/omsk-weather#1]
I am willing to contribute via a README file where I will be describing about the STEPS to contribute in the project.

**Comment by 102** [comment]
Hi @saubhagya-gupta, thanks for the idea. However, I don't think this will be a valuable improvement:

1. this is quite small project without clear purpose
2. why do you want to put contributing guidelines into readme when [separate file could be added for this exact purpose](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)?
